kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-operator
subjects:
- kind: ServiceAccount
  name: namespace-operator
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: namespace-operator
  apiGroup: rbac.authorization.k8s.io
